insert into Genre (Id, Name) values (1, 'POP')
insert into Genre (Id, Name) values (2, 'MPB')
insert into Genre (Id, Name) values (3, 'CLASSIC')
insert into Genre (Id, Name) values (4, 'ROCK')

insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (1, 1, 0, 0.25)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (2, 1, 1, 0.07)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (3, 1, 2, 0.06)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (4, 1, 3, 0.02)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (5, 1, 4, 0.10)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (6, 1, 5, 0.15)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (7, 1, 6, 0.20)

insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (8, 2, 0, 0.30)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (9, 2, 1, 0.05)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (10, 2, 2, 0.10)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (11, 2, 3, 0.15)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (12, 2, 4, 0.20)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (13, 2, 5, 0.25)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (14, 2, 6, 0.30)


insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (15, 3, 0, 0.35)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (16, 3, 1, 0.03)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (17, 3, 2, 0.05)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (18, 3, 3, 0.08)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (19, 3, 4, 0.13)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (20, 3, 5, 0.18)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (21, 3, 6, 0.25)

insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (22, 4, 0, 0.40)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (23, 4, 1, 0.10)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (24, 4, 2, 0.15)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (25, 4, 3, 0.15)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (26, 4, 4, 0.15)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (27, 4, 5, 0.20)
insert into GenreCashback (Id, GenreId, DayOfWeek, Cashback) values (28, 4, 6, 0.40)